### ISSUE TITLE
Pods fail to start - possibly because router configuration not set

### ISSUE THREAD

**Issue by honghuac** [syndesisio/openshift-templates#120]
The state of the routes after the execution of `"oc new-app syndesis -p ROUTE_HOSTNAME=syndesis.127.0.0.1.nip.io -p GITHUB_CLIENT_ID=... -p GITHUB_CLIENT_SECRET=..."` (revealed using `"oc status"`) is seen here: https://gist.github.com/honghuac/3e0a23a3fae393cea2303bd516f4bf74

The pods are showing error messages - https://gist.github.com/honghuac/28bdbb735af11e030f70e7b45b1ba2e4

Seems the router is not configured and the routes are already routing to the various services. Should this router setup be introduced as part of the [quickstart](https://syndesis.io/quickstart/) or [OSE Template readme](https://github.com/syndesisio/syndesis-openshift-templates) instructions?

**Comment by rhuss** [comment]
The route setup is an intrinsic part of the OpenShift installation that Syndesis rely on. It's nothing Syndesis can do about.

For me, it looks like that your OpenShift installation is broken. What OpenShift are you using ? If you use Minishift everything should be already setup for you.

**Comment by honghuac** [comment]
@rhuss Thanks for picking up my issue. I am attempting to install Syndesis on my local OCP 3.6, running on a RHEL 7.4 workstation. Indeed, HAProxy routing configuration needs a proper setup.

Are there any instructions you can share to have the router setup?

**Comment by rhuss** [comment]
@honghuac sorry, that's probably the wrong place here for generic OpenShift questions (and I'm not an OpenShift expert, too). Maybe ask on #openshift on IRC or at github.com/openshift/origin ? Or any other OpenShift support channel, actually.

**Comment by honghuac** [comment]
@rhuss I am recommeding the templates be updated with the setting of the environmental variable ${ROUTE_HOSTNAME}. Far more convenient to do so using templates.

**Comment by honghuac** [comment]
managed to get the pods started, by using system:admin account.
