### ISSUE TITLE
Restricted template is missing reference to pemkeystore IS

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/openshift-templates#122]
https://github.com/syndesisio/syndesis-openshift-templates/blob/master/syndesis-restricted.yml#L482

@jimmidyson is it intentional? Image definition is wrapped with `{Dev}` annotation only.

**Comment by jimmidyson** [comment]
Yes that is intentional as the image is updated by the image stream triggers [defined below](https://github.com/syndesisio/syndesis-openshift-templates/blob/master/syndesis-restricted.yml#L589-L597).
