### ISSUE TITLE
Error converting YAML to JSON - oc create using syndesis templates

### ISSUE THREAD

**Issue by honghuac** [syndesisio/openshift-templates#124]
Following the instructions in the Quickstart, any attempt to use "_oc create -f https://raw.githubusercontent.com/syndesisio/syndesis-openshift-templates/master/syndesis-dev-restricted.yml_" or alternative templates result in this error --
**error: error converting YAML to JSON: yaml: line 120: mapping values are not allowed in this context**

I have attempted to create templates using either developer or system:admin accounts. Has something changed in the templates?

**Comment by paoloantinori** [comment]
Same error here, at least with the file at the time of this commit  60a9ebd

**Comment by paoloantinori** [comment]
The previous version still works fine:
```
oc create -f https://raw.githubusercontent.com/syndesisio/syndesis-openshift-templates/59c47d45f2ef10f2fcff3cbe9c69f6e9d4c4c1ec/syndesis-dev-restricted.yml
```

**Comment by jimmidyson** [comment]
Sorry my bad, broken in #123. Updated PR coming...
