### ISSUE TITLE
Initial delay timeout of syndesis-ui liveness probe

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/openshift-templates#76]
@jimmidyson wrt to upgrade to nginx. I've noticed that initial delay for liveness probe on syndesis-ui is set for just 3 seconds. I expect that those lightweight servers are pretty fast to start-up, but we may end up with "instability" during fresh deployments. 

In fact I've noticed it on Dedicated instance, that UI pod was killed prematurely. Could we raise it to something like 30s at least?

**Comment by rhuss** [comment]
Should be no problem as the other deployments take longer anyway (so increasing it to 30s won't delay the overall startup time of the application)

Feel free to send a PR.
