### ISSUE TITLE
Disable test-support endpoint for TP1 release

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/openshift-templates#97]
Refers to this [parameter](https://github.com/syndesisio/syndesis-openshift-templates/blob/master/generator/01-header.yml.mustache#L103). We should probably switch it to `false` by default or omit from production templates completely.

Cc @rhuss @jimmidyson

**Comment by jimmidyson** [comment]
IMO we should default to false but keep it in the templates - users won't see it but it might help us diagnose issues in prod somehow.

**Comment by rhuss** [comment]
yes, think that fine, just changing the default value
